### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by katsu-skillup** [katsu-skillup/furima-35898#9]
# URL
https://furima-35898.herokuapp.com/

# Basic認証のIDとパスワード
ID: stage
パスワード: 20210401

# 出品者用のメールアドレスとパスワード
メール: sample@gmail.com
パスワード:111aaa

# 購入者用のメールアドレスとパスワード
メール: test@gmail.com
パスワード:222bbb

**Comment by keisukekodama** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

**[修正依頼箇所]**

- [ ] **売却済みの商品の商品編集ページに遷移できてしまう**
ログイン状態の場合で自身が出品した売却済み商品の商品情報編集ページへURLで直接遷移しようとすると、編集ページに遷移できてしまいます。
自身が出品した売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するようにしましょう。


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by katsu-skillup** [comment]
ありがとうございます。editページのアクセルコントロール追加を失念しておりました。修正いたしましたのでご確認ください。

**Comment by mo1015** [comment]
ご提出ありがとうございます！
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/128594378-7e333f55-17eb-475c-a393-76d728baf581.png)

**Comment by katsu-skillup** [comment]
LGTM取得のため、本Issueはclose
